base:
  # The tag used to detect if node is running to build an AMI from it.
  ami_build_tag: is_ami_build
  # Chroot to this path. Usefull if nodereg runs
  # in a container and you want to change the host.
  # Set it to false if no chroot required
  chroot_path: /media/root
  # list of modules to run
  enabled_modules:
    - hostname
    - hosted_zone
    - tinycert
    - etcd

hostname:
  # The glue between hostname components
  glue: ''
  # Consider node tag value
  tag_name: Role
  # Consider IP address
  ip_address:
    # The last N octets of the IP address
    octets: 2
    # The glue between octets
    glue: '-'

hosted_zone:
  # The name of the hosted zone
  name: k8s.com.

# Get certificates from tinycert.org
tinycert:
  email: test
  passphrase: test
  api_key: test
  # Make sure the CA cert is present and recognized system-wide
  # tinycert CA id
  # NOTE: the common name of the certificate is used as filename
  ca_id: 100
  ca_path: /media/root/etc/ssl/certs
  certificates_path: /media/root/etc/ssl/node_certs
  # Make sure the node has a certificate/key for it's FQDN and IP Address
  node_certificate: yes
  # Download other certificate/keys by tinycert id
  # NOTE: the common name of the certificate is used as filename
  certificates: []

etcd:
  client_schema: http
  client_port: 2379
  peer_schema: http
  peer_port: 2380
  drop_in_file: /etc/systemd/system/etcd.service.d/70-initial-cluster.conf
